"""initial_schema_postgres

Revision ID: 3bd20db49909
Revises: 
Create Date: 2026-03-16 19:51:34.592514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bd20db49909'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tools', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mcp_servers', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('schedule_cron', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('office_x', sa.Integer(), nullable=True),
    sa.Column('office_y', sa.Integer(), nullable=True),
    sa.Column('office_station_icon', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('current_task', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_audit_log',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('changes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('performed_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_audit_log_entity_id'), 'crm_audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_crm_audit_log_entity_type'), 'crm_audit_log', ['entity_type'], unique=False)
    op.create_table('crm_companies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('social_profiles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('enrichment_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_companies_name'), 'crm_companies', ['name'], unique=False)
    op.create_table('crm_email_sequences',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('steps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total_enrolled', sa.Integer(), nullable=False),
    sa.Column('total_completed', sa.Integer(), nullable=False),
    sa.Column('total_replied', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_email_sequences_created_at'), 'crm_email_sequences', ['created_at'], unique=False)
    op.create_table('crm_pipelines',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stages', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_pipelines_name'), 'crm_pipelines', ['name'], unique=False)
    op.create_table('crm_smart_lists',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('sort_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('sort_order', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('auto_refresh', sa.Boolean(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_smart_lists_created_at'), 'crm_smart_lists', ['created_at'], unique=False)
    op.create_table('crm_tags',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_tags_name'), 'crm_tags', ['name'], unique=False)
    op.create_table('crm_workflows',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_workflows_created_at'), 'crm_workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_workflows_is_active'), 'crm_workflows', ['is_active'], unique=False)
    op.create_table('integration_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('mcp_server_config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('oauth_tokens_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('connected_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('office_x', sa.Integer(), nullable=False),
    sa.Column('office_y', sa.Integer(), nullable=False),
    sa.Column('notification_prefs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('firebase_uid')
    )
    op.create_table('channel_members',
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('last_read_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('notification_override', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.create_table('crm_contacts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(), nullable=False),
    sa.Column('lifecycle_stage', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_fields', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.Column('next_follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('relationship_strength', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_by_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_contacts_company_id'), 'crm_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_created_at'), 'crm_contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_contacts_lead_score'), 'crm_contacts', ['lead_score'], unique=False)
    op.create_index(op.f('ix_crm_contacts_owner_id'), 'crm_contacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_contacts_stage'), 'crm_contacts', ['stage'], unique=False)
    op.create_table('crm_workflow_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_event', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('trigger_entity_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('actions_executed', sa.Integer(), nullable=False),
    sa.Column('actions_failed', sa.Integer(), nullable=False),
    sa.Column('error_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['crm_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_workflow_executions_executed_at'), 'crm_workflow_executions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_crm_workflow_executions_workflow_id'), 'crm_workflow_executions', ['workflow_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('mentions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_messages', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tools_called', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('num_tool_calls', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['trigger_channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_contact_tags',
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['crm_tags.id'], ),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id')
    )
    op.create_table('crm_deals',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_close_date', sa.DateTime(), nullable=True),
    sa.Column('actual_close_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('loss_reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('loss_reason_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=False),
    sa.Column('deal_health', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['crm_companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['crm_pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_deals_company_id'), 'crm_deals', ['company_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_contact_id'), 'crm_deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_created_at'), 'crm_deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_deals_owner_id'), 'crm_deals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_pipeline_id'), 'crm_deals', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_crm_deals_stage'), 'crm_deals', ['stage'], unique=False)
    op.create_table('crm_notes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('mentions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_notes_contact_id'), 'crm_notes', ['contact_id'], unique=False)
    op.create_table('crm_sequence_enrollments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('next_send_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['crm_email_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sequence_enrollments_contact_id'), 'crm_sequence_enrollments', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_sequence_enrollments_created_at'), 'crm_sequence_enrollments', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_sequence_enrollments_sequence_id'), 'crm_sequence_enrollments', ['sequence_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('folder', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('uploaded_by_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('pushed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'user_id', 'emoji')
    )
    op.create_table('crm_activities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('performed_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('performer_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('performer_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_calendar_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('meeting_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('external_event_id', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('external_calendar_id', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('attendees', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reminder_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('outcome_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_auto_created', sa.Boolean(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_calendar_events_contact_id'), 'crm_calendar_events', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_calendar_events_created_at'), 'crm_calendar_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_calendar_events_deal_id'), 'crm_calendar_events', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_calendar_events_event_type'), 'crm_calendar_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_crm_calendar_events_start_at'), 'crm_calendar_events', ['start_at'], unique=False)
    op.create_index(op.f('ix_crm_calendar_events_status'), 'crm_calendar_events', ['status'], unique=False)
    op.create_table('crm_emails',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('body_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_address', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('to_addresses', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cc_addresses', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('external_message_id', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sequence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sequence_step', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['crm_email_sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_emails_contact_id'), 'crm_emails', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_emails_created_at'), 'crm_emails', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_emails_deal_id'), 'crm_emails', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_emails_sequence_id'), 'crm_emails', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_crm_emails_thread_id'), 'crm_emails', ['thread_id'], unique=False)
    op.create_table('crm_call_recordings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('calendar_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript_segments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcription_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('transcription_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_action_items', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_sentiment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('ai_key_topics', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_objections', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ai_next_steps', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['crm_calendar_events.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_call_recordings_calendar_event_id'), 'crm_call_recordings', ['calendar_event_id'], unique=False)
    op.create_index(op.f('ix_crm_call_recordings_contact_id'), 'crm_call_recordings', ['contact_id'], unique=False)
    op.create_index(op.f('ix_crm_call_recordings_created_at'), 'crm_call_recordings', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_call_recordings_deal_id'), 'crm_call_recordings', ['deal_id'], unique=False)
    op.create_index(op.f('ix_crm_call_recordings_transcription_status'), 'crm_call_recordings', ['transcription_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_call_recordings_transcription_status'), table_name='crm_call_recordings')
    op.drop_index(op.f('ix_crm_call_recordings_deal_id'), table_name='crm_call_recordings')
    op.drop_index(op.f('ix_crm_call_recordings_created_at'), table_name='crm_call_recordings')
    op.drop_index(op.f('ix_crm_call_recordings_contact_id'), table_name='crm_call_recordings')
    op.drop_index(op.f('ix_crm_call_recordings_calendar_event_id'), table_name='crm_call_recordings')
    op.drop_table('crm_call_recordings')
    op.drop_index(op.f('ix_crm_emails_thread_id'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_sequence_id'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_deal_id'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_created_at'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_contact_id'), table_name='crm_emails')
    op.drop_table('crm_emails')
    op.drop_index(op.f('ix_crm_calendar_events_status'), table_name='crm_calendar_events')
    op.drop_index(op.f('ix_crm_calendar_events_start_at'), table_name='crm_calendar_events')
    op.drop_index(op.f('ix_crm_calendar_events_event_type'), table_name='crm_calendar_events')
    op.drop_index(op.f('ix_crm_calendar_events_deal_id'), table_name='crm_calendar_events')
    op.drop_index(op.f('ix_crm_calendar_events_created_at'), table_name='crm_calendar_events')
    op.drop_index(op.f('ix_crm_calendar_events_contact_id'), table_name='crm_calendar_events')
    op.drop_table('crm_calendar_events')
    op.drop_table('crm_activities')
    op.drop_table('reactions')
    op.drop_table('notifications')
    op.drop_table('files')
    op.drop_index(op.f('ix_crm_sequence_enrollments_sequence_id'), table_name='crm_sequence_enrollments')
    op.drop_index(op.f('ix_crm_sequence_enrollments_created_at'), table_name='crm_sequence_enrollments')
    op.drop_index(op.f('ix_crm_sequence_enrollments_contact_id'), table_name='crm_sequence_enrollments')
    op.drop_table('crm_sequence_enrollments')
    op.drop_index(op.f('ix_crm_notes_contact_id'), table_name='crm_notes')
    op.drop_table('crm_notes')
    op.drop_index(op.f('ix_crm_deals_stage'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_pipeline_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_owner_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_created_at'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_contact_id'), table_name='crm_deals')
    op.drop_index(op.f('ix_crm_deals_company_id'), table_name='crm_deals')
    op.drop_table('crm_deals')
    op.drop_table('crm_contact_tags')
    op.drop_table('agent_executions')
    op.drop_table('messages')
    op.drop_index(op.f('ix_crm_workflow_executions_workflow_id'), table_name='crm_workflow_executions')
    op.drop_index(op.f('ix_crm_workflow_executions_executed_at'), table_name='crm_workflow_executions')
    op.drop_table('crm_workflow_executions')
    op.drop_index(op.f('ix_crm_contacts_stage'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_owner_id'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_lead_score'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_created_at'), table_name='crm_contacts')
    op.drop_index(op.f('ix_crm_contacts_company_id'), table_name='crm_contacts')
    op.drop_table('crm_contacts')
    op.drop_table('channel_members')
    op.drop_table('user_profiles')
    op.drop_table('integration_configs')
    op.drop_index(op.f('ix_crm_workflows_is_active'), table_name='crm_workflows')
    op.drop_index(op.f('ix_crm_workflows_created_at'), table_name='crm_workflows')
    op.drop_table('crm_workflows')
    op.drop_index(op.f('ix_crm_tags_name'), table_name='crm_tags')
    op.drop_table('crm_tags')
    op.drop_index(op.f('ix_crm_smart_lists_created_at'), table_name='crm_smart_lists')
    op.drop_table('crm_smart_lists')
    op.drop_index(op.f('ix_crm_pipelines_name'), table_name='crm_pipelines')
    op.drop_table('crm_pipelines')
    op.drop_index(op.f('ix_crm_email_sequences_created_at'), table_name='crm_email_sequences')
    op.drop_table('crm_email_sequences')
    op.drop_index(op.f('ix_crm_companies_name'), table_name='crm_companies')
    op.drop_table('crm_companies')
    op.drop_index(op.f('ix_crm_audit_log_entity_type'), table_name='crm_audit_log')
    op.drop_index(op.f('ix_crm_audit_log_entity_id'), table_name='crm_audit_log')
    op.drop_table('crm_audit_log')
    op.drop_table('channels')
    op.drop_table('agents')
    # ### end Alembic commands ###
