"""add_missing_tables_and_columns

Revision ID: 56c31fa25bd0
Revises: be0ff9c84279
Create Date: 2026-03-20 03:57:02.954636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56c31fa25bd0'
down_revision: Union[str, None] = 'be0ff9c84279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create missing table
    op.create_table('digests',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('digest_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('highlights', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stats', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('week_start', sa.DateTime(), nullable=True),
    sa.Column('week_end', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # 2. Backfill NULLs before setting NOT NULL on agents columns
    op.execute("UPDATE agents SET max_iterations = 5 WHERE max_iterations IS NULL")
    op.execute("UPDATE agents SET autonomy_level = 2 WHERE autonomy_level IS NULL")
    op.execute("UPDATE agents SET temperature = 0.7 WHERE temperature IS NULL")
    op.execute("UPDATE agents SET cost_this_month = 0.0 WHERE cost_this_month IS NULL")

    op.alter_column('agents', 'max_iterations',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('agents', 'autonomy_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.7'))
    op.alter_column('agents', 'custom_tools',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('agents', 'cost_this_month',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))

    # 3. Add missing columns to crm_activities
    op.add_column('crm_activities', sa.Column('chat_signal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('crm_activities', sa.Column('chat_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'crm_activities', 'chat_signals', ['chat_signal_id'], ['id'])

    # 4. Add missing AI columns to crm_contacts
    op.add_column('crm_contacts', sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('crm_contacts', sa.Column('last_ai_analysis_at', sa.DateTime(), nullable=True))
    op.add_column('crm_contacts', sa.Column('ai_tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('crm_contacts', sa.Column('sentiment_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_contacts', 'sentiment_score')
    op.drop_column('crm_contacts', 'ai_tags')
    op.drop_column('crm_contacts', 'last_ai_analysis_at')
    op.drop_column('crm_contacts', 'ai_summary')
    op.drop_constraint(None, 'crm_activities', type_='foreignkey')
    op.drop_column('crm_activities', 'chat_context')
    op.drop_column('crm_activities', 'chat_signal_id')
    op.alter_column('agents', 'cost_this_month',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('agents', 'custom_tools',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('agents', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.7'))
    op.alter_column('agents', 'autonomy_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('agents', 'max_iterations',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.drop_table('digests')
    # ### end Alembic commands ###
