"""Add is_private and is_archived

Revision ID: be0ff9c84279
Revises: 3bd20db49909
Create Date: 2026-03-17 00:58:22.322458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be0ff9c84279'
down_revision: Union[str, None] = '3bd20db49909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('channels', sa.Column('is_archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'is_archived')
    op.drop_column('channels', 'is_private')
    # ### end Alembic commands ###
